"""Add sold field

Revision ID: 411c8271376d
Revises: 68deefd51c15
Create Date: 2026-03-26 13:46:48.858167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "411c8271376d"
down_revision: Union[str, Sequence[str], None] = "68deefd51c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tickets",
        sa.Column("sold", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "sold")
    # ### end Alembic commands ###
