"""Addded relationship with TicketDetails

Revision ID: c7282a2fe53a
Revises: ed75c5aa0fc0
Create Date: 2026-03-26 16:31:42.641980

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c7282a2fe53a"
down_revision: Union[str, Sequence[str], None] = "ed75c5aa0fc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO ticket_details (ticket_id)
        SELECT id FROM tickets
        WHERE id NOT IN (SELECT ticket_id FROM ticket_details)
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
